version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: artifacts-postgres
    environment:
      POSTGRES_DB: artefactik0
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - artifacts-postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: artifacts-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console UI → http://localhost:9001
    volumes:
      - artifacts-minio-data:/data

volumes:
  artifacts-postgres-data:
  artifacts-minio-data: