spring.application.name=Artefactik0
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5433/artefactik0
spring.datasource.username=myuser
spring.datasource.password=secret

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway ? ?????????, ddl-auto=update ??? ??????? ???????
spring.flyway.enabled=false

# Spring MVC
spring.mvc.pathmatch.use-suffix-pattern=false
spring.web.resources.add-mappings=false

# MinIO
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=artefactik0-tasks